### ISSUE TITLE
issues during experiment

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSexperiments#3]
1. 'progress' and 'time' don't move at all
2. Histogram at optomotor seem to show position, not torque
3. "timeslot" should be "period"
4. display could be much larger
5. Histogram does not reset with new period and does not change with period type: torque for yt, sw and optomotor, position for fs.
6. Traces: Position need to reflect actual visual situation, scale: +/-180°
7. Traces: Torque needs different axis than position, but with zero in the middle for both torque and position
8. Histogram bins too large. about 4-6x smaller

**Comment by brembs** [comment]
9. performance indices not shown
10. not save data on "stop", if possible
11. Coupling probably has to be reduced by at least 20% (and inverted)

**Comment by brembs** [comment]
12. Histogram background could indicate test/training period.

**Comment by brembs** [comment]
13. Laser button that switches the laser on/off even when the experiment is not running.

**Comment by brembs** [comment]
Here an example for points 6/7:
![image](https://user-images.githubusercontent.com/4497452/87434095-56f2e700-c5ea-11ea-9051-f2852b1ab156.png)
Left y-axis has arena position from -180° to +180° (-1800..1800), right y-axis is torque. Red is position trace, blue is torque trace.

**Comment by Eanders1** [comment]
14. Not possible to switch tabs while experiment is running
