### ISSUE TITLE
issues on setup tab

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSexperiments#4]
1. Filename: 'return' deletes entry
2. Setup (path): cannot choose folder, path is ignored
3. Zero is added to filename, even though there is a number at end

**Comment by Johann-Schmid** [comment]
1. Changed to one line
2. done
3. not done

**Comment by brembs** [comment]
1 - confirmed, works
2. Path is still ignored, data is written into program folder no matter what I enter into the path form.

**Comment by brembs** [comment]
distributed the issues to separate entries
