### ISSUE TITLE
issues after experiment

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSexperiments#6]
1. Setup tab form values are not saved in XML file (see screenshots) -> changed 3v19
2. Sampling rate is recorded as 20Hz, when it is 72Hz

**Comment by brembs** [comment]
![image](https://user-images.githubusercontent.com/4497452/87432241-067a8a00-c5e8-11ea-923e-5ccaefc9cf18.png)
Not all of the values in "Fly" and "experimental metadata" are saved in the XML-file, e.g., fly name, fly description, ArenaType, metertype, Metadata description.

**Comment by Johann-Schmid** [comment]
2. The sample rate can be configured in the transmission.ini file sample_rate = 72

**Comment by brembs** [comment]
Ideally, the user should not have to enter it, as the user may not know of the actual sampling rate. I know it, but I'm not sure others users will know it.

**Comment by Johann-Schmid** [comment]
1. Issue one is solved in version 3.19

**Comment by brembs** [comment]
remaining issue posted separately
